version: '3'
services:
  nomad:
    build: ./nomad_docker
    volumes:
      - ./nomad_server/config:/etc/nomad
      - ./tmp:/tmp
    command: agent
    ports: 
      - 4646:4646
    networks: 
      - hashicorp
    depends_on:
      - consul-server-1
      - consul-agent-1

  nomad-client:
    build: ./nomad_docker
    command: agent
    volumes:
      - ./nomad_client/config:/etc/nomad
      - ./tmp:/tmp
    depends_on:
      - nomad
    ports: 
      - 5646:5646
    networks: 
      - hashicorp

  consul-agent-1: &consul-agent
    image: consul:latest
    networks:
      - hashicorp
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    <<: *consul-agent

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 2 -ui -client 0.0.0.0"

  vault-1:
    image: vault:1.3.0
    ports:
      - "8200:8200"
      - "8201:8201"
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/file
      - ./vault/logs:/vault/logs
    cap_add:
      - IPC_LOCK
    command: vault server -config /vault/config/config.json

networks:
  hashicorp:
    ipam:
      config:
        - subnet: 172.20.0.0/16
