version: '3'
services:
  nomad:
    build: ./nomad_docker
    volumes:
      - ./nomad_server/config:/etc/nomad
      - ./tmp:/tmp
      - ./nomad_server/data:/nomad/data
    command: agent
    ports: 
      - 4646:4646
    networks: 
      - hashicorp
    depends_on:
      - consul-server-1
      - consul-agent-1

  nomad-client:
    build: ./nomad_docker
    command: agent
    volumes:
      - ./nomad_client/config:/etc/nomad
      - ./nomad_client/data:/nomad/data
      - ./tmp:/tmp
    depends_on:
      - nomad
    ports: 
      - 5646:5646
    networks: 
      - hashicorp

  consul-agent-1: &consul-agent
    image: consul:latest
    networks:
      - hashicorp
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    <<: *consul-agent

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 2 -ui -client 0.0.0.0"
    volumes:
      - ./consul_leader/data:/consul/data

  vault-1:
    build: ./vault
    ports:
      - "8200:8200"
      - "8201:8201"
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/file
      - ./vault/logs:/vault/logs
      - ./vault/rsyslog.d:/etc/rsyslog.d
    cap_add:
      - IPC_LOCK
    networks:
      - hashicorp
    command: vault server -config /vault/config/config.json

  vector:
    image: timberio/vector:0.7.2-alpine
    ports:
      - "9000:9000"
    networks:
      - hashicorp
    volumes:
      - ./vector/vector.toml:/etc/vector/vector.toml:ro
      - ./vector/data:/var/lib/vector:rw
networks:
  hashicorp:
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes: 
  consul_leader: